name: Describe
channels:
  - conda-forge
  - defaults
dependencies:
  - flask=1.1.2=pyh9f0ad1d_0
  - pillow=8.1.2=py39h1a9d4f7_1
  - pip=21.1.1=pyhd8ed1ab_0
  - pip:
    - numpy==1.19.5
    - tensorflow-cpu==2.5.0rc3
    - urllib3==1.26.4
